# Generated by Django 4.2 on 2023-04-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethno_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
        migrations.DeleteModel(
            name='contacts',
        ),
        migrations.DeleteModel(
            name='dishMenu',
        ),
        migrations.DeleteModel(
            name='halls',
        ),
        migrations.DeleteModel(
            name='services',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
