# Generated by Django 4.2 on 2023-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ethno_page', '0002_delete_about_delete_contacts_delete_dishmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='dishMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDishes', models.CharField(max_length=255)),
                ('priceOfDishes', models.IntegerField()),
                ('photoOfDishes', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameHall', models.CharField(max_length=255)),
                ('descriptionHall', models.CharField(max_length=255)),
                ('priceHall', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameService', models.CharField(max_length=255)),
                ('descriptionService', models.CharField(max_length=255)),
                ('priceService', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='socialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
            ],
        ),
    ]
